import { GoogleGenAI } from "@google/genai";

const DEFAULT_FOOD_IMAGE = "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=600&q=80";

// ── UNSPLASH IMAGE FETCH ──
export async function fetchFoodImage(recipeName) {
  const unsplashKey = process.env.UNSPLASH_ACCESS_KEY;
  if (!unsplashKey) return { url: DEFAULT_FOOD_IMAGE, credit: null };

  try {
    const query = encodeURIComponent(`${recipeName} food dish`);
    const res = await fetch(
      `https://api.unsplash.com/search/photos?query=${query}&per_page=1&orientation=landscape`,
      { headers: { Authorization: `Client-ID ${unsplashKey}` } }
    );
    if (!res.ok) throw new Error(`Unsplash: ${res.status}`);
    const data = await res.json();
    if (data.results?.length > 0) {
      const photo = data.results[0];
      return { url: `${photo.urls.regular}&w=600&q=80`, credit: photo.user?.name || null };
    }
    return { url: DEFAULT_FOOD_IMAGE, credit: null };
  } catch (err) {
    console.warn("[Image] Unsplash failed:", err.message);
    return { url: DEFAULT_FOOD_IMAGE, credit: null };
  }
}

// ── GEMINI FLASH IMAGE GENERATION (REST API) ──
export async function generateRecipeImage(recipeName, ingredients) {
  const apiKey = process.env.GEMINI_API_KEY;
  // *** FIXED: Updated to the stable model name ***
  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key=${apiKey}`;

  const prompt = `Professional food photography of "${recipeName}". 
  Main ingredients: ${ingredients.slice(0, 4).join(", ")}.
  Style: bright natural lighting, top-down view, vibrant colors, restaurant quality, 4K.`;

  try {
    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          responseModalities: ["TEXT", "IMAGE"]
        }
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`HTTP ${response.status}: ${errorText}`);
    }

    const data = await response.json();
    const part = data.candidates?.[0]?.content?.parts?.find(p => p.inlineData);

    if (part?.inlineData) {
      const base64 = part.inlineData.data;
      const mimeType = part.inlineData.mimeType || "image/png";
      return {
        url: `data:${mimeType};base64,${base64}`,
        credit: "Generated by Gemini AI"
      };
    }
    throw new Error("No image data in response");
  } catch (err) {
    console.error("[Gemini Image] Failed:", err.message);
    return null; // Your existing fallback to Unsplash will handle this
  }
}

export async function generateRecipeImageImagen(recipeName, ingredients) {
  const apiKey = process.env.GEMINI_API_KEY; // same key works for Imagen
  const url = "https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-generate-001:predict";

  const prompt = `Professional food photography of "${recipeName}" with ${ingredients.slice(0, 3).join(", ")}. Plated beautifully, natural lighting, high resolution, 4K.`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-goog-api-key": apiKey,
    },
    body: JSON.stringify({
      instances: [{ prompt }],
      parameters: {
        sampleCount: 1,
        aspectRatio: "1:1",
      },
    }),
  });

  const data = await response.json();
  if (data.predictions && data.predictions[0]) {
    const base64 = data.predictions[0].bytesBase64Encoded;
    return {
      url: `data:image/png;base64,${base64}`,
      credit: "Generated by Imagen 4.0",
    };
  }
  throw new Error("Imagen failed");
}

// ── GEMINI AI (FREE) ──
let _gemini;
function getGemini() {
  if (!_gemini) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error("GEMINI_API_KEY not set");
    _gemini = new GoogleGenAI({ apiKey });
  }
  return _gemini;
}

export async function generateRecipe(ingredients) {
  const ingredientList = ingredients.join(", ");

  const response = await getGemini().models.generateContent({
    model: "gemini-2.5-flash",
    contents: `I have these ingredients: ${ingredientList}

Suggest a recipe I can make with these ingredients (you can assume I have basic pantry staples like salt, pepper, oil, etc.).

Respond ONLY with a JSON object in this exact format, no markdown, no backticks, no other text:
{
  "name": "Recipe Name",
  "description": "A brief 1-2 sentence description of the dish",
  "cuisine": "Cuisine type (e.g. Italian, Indian, Mexican, Nepali, American)",
  "cooking_time": "Estimated time (e.g. 30 minutes, 1 hour)",
  "servings": 2,
  "ingredients": ["ingredient 1 with amount", "ingredient 2 with amount"],
  "steps": ["Step 1 instruction", "Step 2 instruction", "Step 3 instruction"]
}`,
  });

  const text = response.text;
  const cleaned = text.replace(/```json\s*/g, "").replace(/```\s*/g, "").trim();

  try {
    return JSON.parse(cleaned);
  } catch (parseError) {
    console.error("[AI] Failed to parse Gemini response:", text);
    throw new Error("Failed to parse recipe from AI response");
  }
}

// ── SIMULATED RECIPES (fallback) ──
const recipes = [
  {
    match: ["chicken", "garlic"],
    recipe: {
      name: "Garlic Herb Chicken",
      description: "Juicy pan-seared chicken with a fragrant garlic and herb butter sauce. Restaurant-quality in under 30 minutes.",
      cuisine: "American",
      cooking_time: "25 minutes",
      servings: 2,
      ingredients: ["2 chicken breasts", "4 cloves garlic, minced", "2 tbsp butter", "1 tbsp olive oil", "1 tsp dried thyme", "1 tsp dried rosemary", "Salt and pepper to taste", "Fresh parsley for garnish"],
      steps: ["Pat chicken dry and season with salt, pepper, thyme, and rosemary", "Heat olive oil in a skillet over medium-high heat", "Sear chicken for 6-7 minutes per side until golden", "Add butter and garlic, cook 1 minute until fragrant", "Baste chicken with garlic butter for 2 minutes", "Rest 5 minutes, then slice and garnish with parsley"],
    },
  },
  {
    match: ["chicken", "ginger", "soy"],
    recipe: {
      name: "Ginger Soy Chicken Stir-Fry",
      description: "Quick and savory stir-fry with tender chicken, fresh ginger, and a glossy soy glaze. Perfect over steamed rice.",
      cuisine: "Asian",
      cooking_time: "20 minutes",
      servings: 2,
      ingredients: ["300g chicken thigh, sliced", "2 tbsp soy sauce", "1 tbsp fresh ginger, grated", "2 cloves garlic, minced", "1 tbsp sesame oil", "1 tbsp honey", "1 tsp cornstarch", "2 green onions, sliced"],
      steps: ["Mix soy sauce, honey, sesame oil, and cornstarch for the sauce", "Heat oil in a wok over high heat", "Stir-fry chicken for 4-5 minutes until golden", "Add ginger and garlic, cook 30 seconds", "Pour sauce over chicken and toss to coat", "Cook 1-2 minutes until sauce thickens", "Serve over rice, garnish with green onions"],
    },
  },
  {
    match: ["egg", "tomato"],
    recipe: {
      name: "Tomato Egg Stir-Fry",
      description: "Silky scrambled eggs in a sweet and tangy tomato sauce. A Chinese home-cooking classic ready in 15 minutes.",
      cuisine: "Chinese",
      cooking_time: "15 minutes",
      servings: 2,
      ingredients: ["4 large eggs", "3 ripe tomatoes, wedged", "2 tbsp vegetable oil", "1 tbsp sugar", "1 tsp salt", "2 green onions, chopped", "1 tsp sesame oil"],
      steps: ["Beat eggs with a pinch of salt", "Heat 1 tbsp oil in wok, scramble eggs into soft curds, set aside", "Add remaining oil, cook tomatoes 3-4 minutes until soft", "Add sugar and salt, stir until juices release", "Return eggs and fold gently together", "Drizzle sesame oil, garnish with green onions"],
    },
  },
  {
    match: ["potato", "onion"],
    recipe: {
      name: "Crispy Aloo Fry",
      description: "Golden spiced potatoes with caramelized onions. A beloved Nepali side dish that pairs with anything.",
      cuisine: "Nepali",
      cooking_time: "25 minutes",
      servings: 3,
      ingredients: ["4 medium potatoes, cubed", "1 large onion, sliced", "2 tbsp oil", "1 tsp turmeric", "1 tsp cumin seeds", "1 tsp chili flakes", "Salt to taste", "Fresh cilantro"],
      steps: ["Boil potato cubes until just tender, about 8 minutes, then drain", "Heat oil, add cumin seeds and let them splutter", "Add onions and cook until golden, about 5 minutes", "Add potatoes, turmeric, chili flakes, and salt", "Spread in a single layer, let crisp without stirring for 3 minutes", "Flip and crisp the other side. Garnish with cilantro"],
    },
  },
  {
    match: ["rice", "egg"],
    recipe: {
      name: "Golden Egg Fried Rice",
      description: "Restaurant-style fried rice with perfectly separated grains coated in egg. High heat and cold rice are the secrets.",
      cuisine: "Chinese",
      cooking_time: "15 minutes",
      servings: 2,
      ingredients: ["3 cups cold cooked rice", "3 eggs", "2 tbsp soy sauce", "1 tbsp sesame oil", "3 green onions, chopped", "2 cloves garlic, minced", "1 cup mixed vegetables", "2 tbsp vegetable oil"],
      steps: ["Beat eggs. Break up cold rice with hands to separate grains", "Heat oil in wok over highest heat until smoking", "Pour in eggs, scramble 15 seconds until just set", "Add rice and stir-fry vigorously for 2 minutes", "Push rice aside, add garlic and vegetables, cook 1 minute", "Mix everything, add soy sauce and sesame oil", "Toss until every grain is coated. Top with green onions"],
    },
  },
  {
    match: ["pasta", "tomato"],
    recipe: {
      name: "Classic Pomodoro Pasta",
      description: "Simple Italian pasta with rich fresh tomato sauce, garlic, and basil. Proof that less is more.",
      cuisine: "Italian",
      cooking_time: "25 minutes",
      servings: 2,
      ingredients: ["250g spaghetti", "4 ripe tomatoes, diced", "3 cloves garlic, sliced", "3 tbsp olive oil", "Fresh basil leaves", "1 tsp sugar", "Salt and pepper", "Parmesan for serving"],
      steps: ["Boil salted water, cook spaghetti per package directions", "Heat olive oil, add sliced garlic, cook 1 minute until golden", "Add tomatoes, sugar, salt, and pepper", "Simmer 12-15 minutes until sauce thickens", "Reserve pasta water, drain spaghetti", "Toss pasta into sauce with a splash of pasta water", "Top with torn basil and grated Parmesan"],
    },
  },
  {
    match: ["lentil"],
    recipe: {
      name: "Comforting Dal",
      description: "Hearty, creamy lentil stew spiced with cumin and turmeric. The ultimate comfort food that feeds the soul.",
      cuisine: "Indian",
      cooking_time: "35 minutes",
      servings: 4,
      ingredients: ["1 cup red lentils", "1 onion, diced", "2 tomatoes, chopped", "3 cloves garlic", "1 inch ginger, grated", "1 tsp turmeric", "1 tsp cumin seeds", "1 tsp garam masala", "2 tbsp ghee", "Fresh cilantro"],
      steps: ["Wash lentils until water runs clear, boil with turmeric and 3 cups water", "Simmer 20 minutes until completely soft and creamy", "Heat ghee in a pan, add cumin seeds until they splutter", "Add onion, cook until deeply golden, about 7 minutes", "Add garlic, ginger, and tomatoes, cook until soft", "Add garam masala, pour tempering over lentils", "Stir well and garnish with cilantro"],
    },
  },
  {
    match: ["buff", "onion"],
    recipe: {
      name: "Nepali Buff Curry",
      description: "A rich and aromatic buffalo meat curry slow-cooked with onions, tomatoes, and traditional Nepali spices.",
      cuisine: "Nepali",
      cooking_time: "50 minutes",
      servings: 4,
      ingredients: ["500g buffalo meat, cubed", "2 large onions, sliced", "3 tomatoes, pureed", "4 cloves garlic", "1 inch ginger", "2 tsp cumin powder", "1 tsp turmeric", "2 tsp coriander powder", "1 tsp chili powder", "3 tbsp oil", "Fresh cilantro"],
      steps: ["Heat oil, cook onions until deep golden brown, about 10 minutes", "Add garlic and ginger, cook 1 minute", "Add all spice powders, cook 30 seconds", "Add buffalo meat and sear on all sides for 5 minutes", "Pour in tomato puree and 1 cup water", "Cover and simmer on low for 35-40 minutes until tender", "Garnish with cilantro and serve with steamed rice"],
    },
  },
  {
    match: ["paneer", "spinach"],
    recipe: {
      name: "Palak Paneer",
      description: "Creamy spinach curry with soft paneer cubes. A North Indian classic loved worldwide.",
      cuisine: "Indian",
      cooking_time: "30 minutes",
      servings: 3,
      ingredients: ["250g paneer, cubed", "300g fresh spinach", "1 onion, chopped", "2 tomatoes, chopped", "3 cloves garlic", "1 inch ginger", "1 tsp cumin seeds", "1 tsp garam masala", "2 tbsp cream", "2 tbsp oil"],
      steps: ["Blanch spinach in boiling water for 2 minutes, then ice bath", "Blend spinach into a smooth puree", "Heat oil, add cumin seeds, then onion until soft", "Add garlic, ginger, and tomatoes, cook until mushy", "Add spinach puree, garam masala, and salt", "Simmer 5 minutes, add paneer cubes", "Stir in cream, cook 2 more minutes, and serve"],
    },
  },
];

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

export function simulateRecipe(ingredients) {
  const lower = ingredients.map((i) => i.toLowerCase());

  let bestMatch = null;
  let bestScore = 0;

  for (const entry of recipes) {
    const score = entry.match.filter((m) =>
      lower.some((ing) => ing.includes(m) || m.includes(ing))
    ).length;
    if (score > bestScore) {
      bestScore = score;
      bestMatch = entry.recipe;
    }
  }

  if (bestMatch && bestScore >= 1) return { ...bestMatch };

  return {
    name: `${capitalize(ingredients[0])} ${["Medley", "Bowl", "Skillet"][Math.floor(Math.random() * 3)]}`,
    description: `A creative dish combining ${ingredients.slice(0, 3).join(", ")} with bold seasoning and simple technique.`,
    cuisine: "Fusion",
    cooking_time: "30 minutes",
    servings: 2,
    ingredients: ingredients.map((i, idx) => {
      const amounts = ["200g", "1 cup", "2 tbsp", "3 cloves", "1 large", "100g"];
      return `${amounts[idx % amounts.length]} ${i}`;
    }).concat(["2 tbsp oil", "Salt and pepper to taste"]),
    steps: [
      `Wash and prepare all ingredients. Dice ${ingredients[0]} into even pieces`,
      "Heat oil in a large pan over medium-high heat",
      `Add ${ingredients[0]} and cook 3-4 minutes until starting to brown`,
      ingredients.length > 1 ? `Add ${ingredients.slice(1).join(", ")} and cook 3 more minutes` : "Season generously with your favorite spices",
      "Adjust seasoning with salt and pepper",
      "Serve hot with rice or bread",
    ],
  };
}